services:
  postman_db:
    image: postgres:16
    container_name: postman_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

  postman_service:
    build:
      context: ..
      dockerfile: postman/Dockerfile
    container_name: postman_service
    restart: always
    env_file:
      - .env
      - ../.env
    depends_on:
      postman_db:
        condition: service_started
      kafka-1:
        condition: service_healthy
      kafka-2:
          condition: service_healthy
      kafka-3:
          condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./src:/home/postman_admin/app/postman/src
      - ./migrations:/home/postman_admin/app/postman/migrations

volumes:
  db_data: