include:
  - ./postman/docker-compose.yaml
  - ./guard/docker-compose.yaml
  - ./magician/docker-compose.yaml
  - ./scavenger/docker-compose.yaml

services:
  kafka-1:
    image: apache/kafka-native
    container_name: kafka-1
    env_file:
      - .env
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      KAFKA_LISTENERS: CONTROLLER://kafka-1:9091,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka-1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost:9093"]
      interval: 5s
      retries: 12
    volumes:
      - kafka1_data:/var/lib/kafka/data
    networks:
      - internal_network

  kafka-2:
    image: apache/kafka-native
    container_name: kafka-2
    env_file:
      - .env
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      KAFKA_LISTENERS: CONTROLLER://kafka-2:9091,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka-2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost:9093"]
      interval: 5s
      retries: 12
    volumes:
      - kafka2_data:/var/lib/kafka/data
    networks:
      - internal_network

  kafka-3:
    image: apache/kafka-native
    container_name: kafka-3
    env_file:
      - .env
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      KAFKA_LISTENERS: CONTROLLER://kafka-3:9091,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka-3:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost:9093"]
      interval: 5s
      retries: 12
    volumes:
      - kafka3_data:/var/lib/kafka/data
    networks:
      - internal_network

  kafka-ui:
      image: kafbat/kafka-ui
      container_name: kafka-ui
      ports:
        - 8080:8080
      env_file:
        - .env
      environment:
        DYNAMIC_CONFIG_ENABLED: "true"
        KAFKA_CLUSTERS_0_NAME: local
        KAFKA_CLUSTERS_0_READONLY: "false"
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      depends_on:
        - kafka-1
        - kafka-2
        - kafka-3
      networks:
        - public_network
        - internal_network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - ./db/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./db/redis/users.acl:/usr/local/etc/redis/users.acl
      - redis_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - internal_network


volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data:
  redis_data:

networks:
  public_network:
  internal_network:
    internal: true